FROM node:14-alpine as build

RUN npm install -g @vercel/ncc@0.34.0

USER node

RUN mkdir /home/node/app
WORKDIR /home/node/app

COPY ./package.json ./package-lock.json ./

RUN npm install --production

COPY --chown=node:node . .

RUN npm run build

RUN mv wait-for-it.sh ./dist/

FROM node:14-alpine

RUN apk update && apk add --no-cache bash

USER node
RUN mkdir /home/node/app
WORKDIR /home/node/app

COPY --from=build /home/node/app/dist ./
