version: "3.7"
services:
  server:
    build: .
    command: sh -c './wait-for-it.sh -t 0 db:5432 -- npm start'
    depends_on:
      - db
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    env_file: .env
    ports:
      - 4001:4001 # Auth Server
      - 4000:4000 # Apollo Server
  db:
    image: postgres:13.0-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
